CREATE TABLE AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL(
	ID bigint  NOT NULL,
	MERCHANT_ID int NOT NULL,
	TRANSACTION_ID varchar(100) NOT NULL,
	CLIENT_ID int NULL,
	CUSTOMER_PHONE_NO varchar(20) NULL,
	CUSTOMER_EMAIL varchar(100) NULL,
	CUSTOMER_ID varchar(100) NULL,
	REMARKS varchar(4000) NULL,
	PAYMENT_START_URL varchar(250) NULL,
	RETURN_URLS varchar(4000) NULL,
	POST_DATA varchar(4000) NULL,
	CUSTOM_PARAMETERS varchar(4000) NULL,
	IS_PAYMENT_SUCCESSFUL bit NULL,
	LAST_VISITED_URL varchar(250) NULL,
	IS_BACK_PRESSED bit NULL,
	IS_TRANSACTION_WAS_COMPLETED bit NULL,
	IS_FETCHED_OTP_DETAILS bit NULL,
	IS_OTP_DETECTED bit NULL,
	HAVE_SMS_PERMISSION bit NULL,
	IS_OTP_APPROVED bit NULL,
	ERROR_CODE int NULL,
	ERROR_MSG varchar(250) NULL,
	BROWSER_SESSION_START_TIME varchar(30) NOT NULL,
	BROWSER_SESSION_FINISH_TIME varchar(30) NOT NULL,
	ROW_INSERTION_DATETIME datetime NULL,
	ROW_UPDATION_DATETIME datetime NULL,
	ROW_ACTION_COUNT int NULL,
	THEME_ID int NULL,
	USESD_LANGUAGE int NULL,
	ORDER_ID varchar(250) NULL,
	PAYMENT_STATUS_CHANGE_DATE datetime NULL,
 CONSTRAINT UX_AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL UNIQUE NONCLUSTERED 
(
	MERCHANT_ID ASC,
	TRANSACTION_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY
) ON PRIMARY

GO
/****** Object:  Table dbo.AGGREGATOR_ANDROID_SDK_CLIENT_TYPE_ID_MASTER_TBL    Script Date: 7/7/2020 9:17:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE dbo.AGGREGATOR_ANDROID_SDK_CLIENT_TYPE_ID_MASTER_TBL(
	CLIENT_TYPE_ID int NOT NULL,
	CLIENT_TYPE varchar(100) NOT NULL,
UNIQUE NONCLUSTERED 
(
	CLIENT_TYPE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY,
UNIQUE NONCLUSTERED 
(
	CLIENT_TYPE_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON PRIMARY
) ON PRIMARY

GO
/****** Object:  Table dbo.AGGREGATOR_BANK_OTP_URLS_TBL    Script Date: 7/7/2020 9:17:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE dbo.AGGREGATOR_BANK_OTP_URLS_TBL(
	BANK_NAME varchar(100) NULL,
	BANK_URL varchar(max) NULL,
	ROW_INSERTION_DATETIME datetime NULL,
	ROW_UPDATION_DATETIME datetime NULL,
	ROW_ACTION_COUNT int NULL,
	IS_PAGE_TO_BE_RESPONSIVE bit NOT NULL,
	IS_OTP_URL bit NOT NULL,
	IS_PAGE_NETBANKING_SUBMISSION_PAGE bit NOT NULL,
	PAGE_CUSTOMIZATION_JS_CODE varchar(max) NOT NULL,
	NET_BANKING_PAGE_SUBMISSIOON_JS_CODE varchar(max) NOT NULL,
	OTP_LENGTH int NOT NULL,
	JS_EXECUTION_ERROR varchar(4000) NULL,
	JS_ERROR_DATETIME datetime NULL,
	IS_JS_ERROR_OCCURRED bit NULL,
	PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS varchar(4000) NOT NULL,
	OTP_PAGE_SUBMISSION_JS_CODE varchar(max) NULL,
	IS_NETBANKING_LOGIN_PAGE bit NOT NULL,
	JS_CODE_TO_GET_CUSTOMER_ID varchar(max) NULL,
	IS_NETBANKING_PAGE bit NOT NULL,
	JS_CODE_TO_SET_CUSTOMER_ID varchar(max) NULL,
	IS_AUTO_OTP_SUBMIT_DISABLED bit NULL,
	IS_GENERIC_OTP_FILLING_JS_CODE_DISABLED bit NULL
) ON PRIMARY TEXTIMAGE_ON PRIMARY

GO
ALTER TABLE dbo.AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL ADD  DEFAULT (getdate()) FOR ROW_INSERTION_DATETIME
GO
ALTER TABLE dbo.AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL ADD  DEFAULT (getdate()) FOR ROW_UPDATION_DATETIME
GO
ALTER TABLE dbo.AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL ADD  DEFAULT ((0)) FOR ROW_ACTION_COUNT
GO
ALTER TABLE dbo.AGGREGATOR_BANK_OTP_URLS_TBL ADD  DEFAULT ((0)) FOR IS_PAGE_NETBANKING_SUBMISSION_PAGE
GO
ALTER TABLE dbo.AGGREGATOR_BANK_OTP_URLS_TBL ADD  DEFAULT ((0)) FOR OTP_LENGTH
GO
ALTER TABLE dbo.AGGREGATOR_BANK_OTP_URLS_TBL ADD  DEFAULT ('') FOR PAGE_CUSTOMIZATION_JS_CODE_FOR_IOS
GO
ALTER TABLE dbo.AGGREGATOR_BANK_OTP_URLS_TBL ADD  DEFAULT ((0)) FOR IS_NETBANKING_LOGIN_PAGE
GO
ALTER TABLE dbo.AGGREGATOR_BANK_OTP_URLS_TBL ADD  DEFAULT ((0)) FOR IS_NETBANKING_PAGE
GO
ALTER TABLE dbo.AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL  WITH CHECK ADD  CONSTRAINT FK_AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL__MERCHANT_ID__PINE_PG_MERCHANT_DETAIL_TBL_MERCHANT_ID FOREIGN KEY(MERCHANT_ID)
REFERENCES dbo.PINE_PG_MERCHANT_DETAIL_TBL (MERCHANT_ID)
GO
ALTER TABLE dbo.AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL CHECK CONSTRAINT FK_AGGREGATOR_ANDROID_BROWSER_TXN_DETAILS_TBL__MERCHANT_ID__PINE_PG_MERCHANT_DETAIL_TBL_MERCHANT_ID
GO
