namespace ExpressCheckoutContracts.Constants.FluentValidationRuleSet
{
    public class ConstantRuleSetName
    {
        public const string CUSTOMER_SAVED_CARD_INSERTION_VALIDATION = "CUSTOMER_SAVED_CARD_INSERTION_VALIDATION";
        public const string CUSTOMER_SAVED_CARD_DELETE_VALIDATION = "CUSTOMER_SAVED_CARD_DELETE_VALIDATION";
        public const string CUSTOMER_SAVED_CARD_FETCH_VALIDATION = "CUSTOMER_SAVED_CARD_FETCH_VALIDATION";
        public const string MERCHANT_DATA_BASIC_VALIDATION = "MERCHANT_DATA_BASIC_VALIDATION";
        public const string CUSTOMER_ID_PRESENT_VALIDATION = "CUSTOMER_ID_PRESENT_VALIDATION";
        public const string CARD_DATA_PRESENT_IN_REQUEST_VALIDATION = "CARD_DATA_PRESENT_IN_REQUEST_VALIDATION";
        public const string SAVED_CARD_ID_PRESENT_VALIDATION = "SAVED_CARD_ID_PRESENT_VALIDATION";
        public const string CREATE_CUSTOMER_VALIDATION = "CREATE_CUSTOMER_VALIDATION";
        public const string UPDATE_CUSTOMER_VALIDATION = "UPDATE_CUSTOMER_VALIDATION";
        public const string PURCHASE_TXN_VALIDATION = "PURCHASE_TXN__VALIDATION";
        public const string ANDROID_SESSION_DETAIL_INSERTION_VALIDATION = "ANDROID_SESSION_DETAIL_INSERTION_VALIDATION";
        public static readonly string PURCHASE_TXN_ORDER_UPDATION_VALIDATION;
      //  public const string ANDROID_SESSION_DETAIL_INSERTION_VALIDATION = "ANDROID_SESSION_DETAIL_INSERTION_VALIDATION";
    }
}